### ISSUE TITLE
[1.X] Test suite with PEST

### ISSUE THREAD

**Issue by 0x35FF** [waveygroup/laravel-gravatar#5]
We will be writing a full test suite for the package using PEST in the coming days. 

If anyone has the time, and would like to contribute, feel feee to add these and submit a pull request.

**Comment by debugdotdog** [comment]
Closing this for now; We will revisit a test suite for the next major release for Laravel Gravatar. If anyone has the time to work on this, please feel free and submit a PR! 😄
